README_TEMPLATE = """# {name}

## Overview

Describe your project here.

## Features

- Built with Blocktracex CLI
- Professional project structure

## Installation

pip install -r requirements.txt

## Usage

Document how to use the project.

## Development

Generated by Blocktracex CLI.
"""

GITIGNORE_TEMPLATE = """.venv/
__pycache__/
*.pyc
.vscode/
.idea/
.env
"""

CHANGELOG_TEMPLATE = """# Changelog

## v0.1.0

- Initial project generated by Blocktracex CLI.
"""

CONTRIBUTING_TEMPLATE = """# Contributing

1. Fork the repository.
2. Create a feature branch.
3. Commit your changes.
4. Submit a Pull Request.
"""

LICENSE_TEMPLATE = """MIT License

Copyright (c) 2026 Blocktracex
"""
BTX_CONFIG_TEMPLATE = """
[project]
name = "{name}"
version = "0.1.0"

[python]
version = "3.13"

[git]
enabled = true
"""